config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  resources :users

  resources :sessions, only: %i[new create destroy]

  resources :instructors, only: [:show], param: :instructor_id do
    get 'past_challenges', on: :member, to: 'instructors#show_prev_challenges', as: 'past_challenges'
    get 'upcoming_challenges', on: :member, to: 'instructors#show_future_challenges', as: 'upcoming_challenges'
  end

  root 'sessions#new'
  get '/login', to: 'sessions#new', as: 'login'
  post '/login', to: 'sessions#create'
  get '/instructor_signup/:token/', to: 'instructors#new', as: 'instructor_signup'
  post '/instructor_signup/:token/', to: 'instructors#create'
  get '/signout', to: 'sessions#destroy', as: 'signout'

  get 'password/reset', to: 'password_resets#new'
  post 'password/reset', to: 'password_resets#create'
  get   'password/reset/edit', to: 'password_resets#edit'
  patch 'password/reset/edit', to: 'password_resets#update'

  get '/trainee_signup', to: 'trainee_signup#new', as: 'trainee_signup'
  post '/trainee_signup', to: 'trainee_signup#create'
  get 'instructor_referral', to: 'instructor_referral#index'
  post 'instructor_referral', to: 'instructor_referral#create'

  get '/todo_list', to: 'todo_list#show', as: 'todo_list'
  patch '/todo_list/mark_as_completed', to: 'todo_list#mark_as_completed', as: 'mark_as_complete'

  get '/trainees/:trainee_id', to: 'challenges#show_challenge_trainee', as: 'show_challenge_trainee'

  get '/trainees/:trainee_id/edit_todo_list/:challenge_id', to: 'todo_list#edit', as: 'edit_trainee_todo_list'
  patch '/trainees/:trainee_id/challenges/:challenge_id', to: 'todo_list#update', as: 'update_trainee_todo_list'

  get 'challenges', to: 'trainees#show_challenges', as: 'show_challenges'
  get '/view_challenge_tasks', to: 'view_challenge_tasks#index', as: 'view_challenge_tasks'
  get 'challenges/:id/challenge_details', to: 'view_challenge_tasks#challenge_details',
                                          as: 'view_challenge_tasks_detail'

  patch 'challenges/:id/todo_list_update', to: 'todo_list#todo_list_update', as: 'todo_list_patch' # update (as needed)
  get 'challenges/:id/todo_list_update', to: 'todo_list#todo_list_update', as: 'todo_list_update' # update (as needed)

  get '/view_trainees', to: 'view_trainees#index', as: 'view_trainees'
  get 'view_trainees/:id/profile_details', to: 'view_trainees#profile_details', as: 'trainee_profile_details'
  get 'view_trainees/:id/challenges', to: 'view_trainees#challenges', as: 'trainee_challenges'
  get 'view_trainees/:trainee_id/challenges/:challenge_id/progress', to: 'view_trainees#progress',
                                                                     as: 'trainee_challenge_progress'

  resources :challenges do
    member do
      get 'edit', to: 'challenges#edit'
      post 'update', to: 'challenges#update', as: 'update'
      get 'add_trainees', to: 'challenges#add_trainees' # This defines the "Add Users" action for a specific challenge
      post 'update_trainees', to: 'challenges#update_trainees' # This defines the action to handle form submission
      get '/delete_trainee', as: 'delete_trainee', controller: 'challenges', action: 'delete_trainee'
    end
  end

  resources :challenges do
    get '/trainees', controller: 'challenges', action: 'trainees_list', constraints: { query_string: /(.+)?/ },
                     as: 'list_trainees'
    get 'task_progress', on: :member, as: 'graph'
  end
  post 'filter_data' => 'challenges#filter_data'

  get '/profile', to: 'profiles#show', as: 'profile'
  get '/edit_profile', to: 'profiles#edit', as: 'edit_profile'
  patch '/update_profile', to: 'profiles#update', as: 'update_profile'

  get 'trainee_profile', to: 'trainee_profile#show'
  get 'edit_trainee_profile', to: 'trainee_profile#edit'
  patch 'trainee_profile', to: 'trainee_profile#update'
end

app/models/instructor.rb
# frozen_string_literal: true

class Instructor < ApplicationRecord
  belongs_to :user
  has_many :challenge
end

app/controllers/instructor_controller.rb
class InstructorController < ApplicationController
    def new 
        puts params[:token]
        token = InstructorReferral.find_by(token: params[:token])
        if !(token.present? && 
             token.expires > DateTime.now &&
             !token.is_used? )
            @token_invalid = true
        end
        @instructor = Instructor.new
        @user = User.new
    end

    def create

        """
        Display customised error message if inputs are invalid
        commenting them as of now
        if user_params[:email] == '' or user_params[:password] == ''
            flash[:error] = 'Incorrect email or password. Please try again.'
            redirect_to instructor_signup_path
            return
        end
        """

        if user_params[:password] != user_params[:confirm_password]
            flash[:error] = 'Password Mismatch.'
            redirect_to instructor_signup_path
            return
        end

        specific_user_params = {
            email: user_params[:email],
            password: user_params[:password],
            user_type: 'Instructor'
        }
        @user = User.new(specific_user_params)

        if valid_inputs? 
            puts "Valid email"
            if @user.save 
    
               specific_instructor_params = {
                    user_id: @user.id,
                    first_name: user_params[:first_name],
                    last_name: user_params[:last_name],
                }

               @instructor = Instructor.new(specific_instructor_params)
               if @instructor.save
                    flash[:notice] = "Welcome, #{@instructor.first_name}!"
                    InstructorReferral.find_by(token: params[:token]).update(is_used: true)
                    session[:user_id] = @user.id
                    redirect_to user_path(session[:user_id])
               end
            end  
        else
            #flash.now[:error] = "Please enter valid email and try again." 
            render 'new'
        end
    end

    def user_params
        params.require(:user).permit(:email, :password, :confirm_password, :first_name, :last_name)
    end

    def valid_inputs?
        email_valid = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i.match?(user_params[:email])
        email_valid
    end
end

app/controllers/instructors_controller.rb
# frozen_string_literal: true

require 'will_paginate/array'

class InstructorsController < ApplicationController
  def new
    puts params[:token]
    token = InstructorReferral.find_by(token: params[:token])
    unless token.present? &&
           token.expires > DateTime.now &&
           !token.is_used?
      @token_invalid = true
    end
    @instructor = Instructor.new
    @user = User.new
  end

  def index; end

  def create
    if user_params[:password] != user_params[:confirm_password]
      flash[:error] = 'Password Mismatch.'
      redirect_to instructor_signup_path
      return
    end

    specific_user_params = {
      email: user_params[:email],
      password: user_params[:password],
      user_type: 'Instructor'
    }
    @user = User.new(specific_user_params)

    if valid_inputs?
      puts 'Valid email'
      if @user.save

        specific_instructor_params = {
          user_id: @user.id,
          first_name: user_params[:first_name],
          last_name: user_params[:last_name]
        }

        @instructor = Instructor.new(specific_instructor_params)
        if @instructor.save
          flash[:notice] = "Welcome, #{@instructor.first_name}!"
          InstructorReferral.find_by(token: params[:token]).update(is_used: true)
          session[:user_id] = @user.id
          redirect_to user_path(session[:user_id])
        end
      end
    else
      # flash.now[:error] = "Please enter valid email and try again."
      render 'new'
    end
  end

  def show
    if user_signed_in?
      today = Date.today
      @instructor = Instructor.find(params[:instructor_id])
      @user_name_from_session = @instructor.first_name
      instructor_id = params[:instructor_id]
      @challenges = Challenge.where('"instructor_id" = ? AND "startDate" <= ? AND "endDate" >= ?', instructor_id,
                                    today, today).order('"endDate" ASC')
      @challenges = @challenges.paginate(page: params[:page], per_page: 7)
      @is_instructor = true if @instructor
      render :show, challenges: @challenges
    else
      redirect_to root_path
    end
  end

  def show_prev_challenges
    if user_signed_in?
      today = Date.today
      @instructor = Instructor.find(params[:instructor_id])
      @user_name_from_session = @instructor.first_name
      instructor_id = params[:instructor_id]
      @challenges = Challenge.where('"instructor_id" = ? AND "startDate" <= ? AND "endDate" <= ?', instructor_id,
                                    today, today).order('"endDate" ASC')
      @challenges = @challenges.paginate(page: params[:page], per_page: 7)
      @is_instructor = true if @instructor
      render :show_prev_challenges, challenges: @challenges
    else
      redirect_to root_path
    end
  end

  def show_future_challenges
    if user_signed_in?
      today = Date.today
      @instructor = Instructor.find(params[:instructor_id])
      @user_name_from_session = @instructor.first_name
      instructor_id = params[:instructor_id]
      @challenges = Challenge.where('"instructor_id" = ? AND "startDate" > ? AND "endDate" >= ?', instructor_id,
                                    today, today).order('"endDate" ASC')
      @challenges = @challenges.paginate(page: params[:page], per_page: 7)
      @is_instructor = true if @instructor
      render :show_future_challenges, challenges: @challenges
    else
      redirect_to root_path
    end
  end

  def user_params
    params.require(:user).permit(:email, :password, :confirm_password, :first_name, :last_name)
  end

  def valid_inputs?
    /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i.match?(user_params[:email])
  end
end

app/helpers/instructor_helper.rb
# frozen_string_literal: true

module InstructorHelper
end

app/views/instructors/new.html.erb
<!-- app/views/users/new.html.erb -->
<%= render 'main/navbar' %>


<div class="container">
    <div class="form-box">
    <div class="row">
    <div class="col-md-6 col-md-offset-3" style="margin-top: 20%;">
    <% if @token_invalid %>
        <%= content_tag :h3, "Token is invalid. Please request for another.", class: 'text-center' %>
    <% else %>
    <% if flash[:success] %>
        <%= content_tag :h3, flash[:success], class: 'text-center' %>
    <% elsif flash[:error] %>
        <%= content_tag :h3, flash[:error], class: 'text-center' %>
    <% end %>

    
    <h1>Sign up</h1>
    <%= form_with model: @user, url: instructor_signup_path, data: {turbo: false} do |f| %>
        <!-- User Fields -->
        <div class="form-field">
            <%= f.label :email, 'Email' %>
            <%= f.email_field :email, id: 'user_email', class: "form-control" %>
        </div>

        <div class="form-field">
            <%= f.label :password, 'Password' %>
            <%= f.password_field :password, id: 'user_password', class: "form-control" %>
        </div>

        <div class="form-field">
            <%= f.label :confirm_password, 'Confirm Password' %>
            <%= f.password_field :confirm_password, id: 'user_confirm_password', class: "form-control" %>
        </div>

        <div class="form-field">
            <%= f.label :first_name, 'First Name' %>
            <%= f.text_field :first_name, id: 'user_first_name', class: "form-control" %>
        </div>

        <div class="form-field">
            <%= f.label :last_name, 'Last Name' %>
            <%= f.text_field :last_name, id: 'user_last_name', class: "form-control" %>
        </div>

        <div class="form-field">
            <%= f.submit 'Sign Up', class: "btn btn-primary" %>
        </div>
    <% end %>
    <% end %>
        </div>
        </div>
    </div>
</div>

app/views/instructors/show.html.erb
<style>
  .welcome-message h4 {
    color: black;
  }
  .create-challenge-btn {
    position: fixed;
    bottom: 2rem;
    right: 2rem;
  }
  .indiChallenge {
    border: solid 2px;
    overflow: hidden;
    margin: 1% 0;
  }
  .challenge-content {
    padding: 0 1% 1% 1%
  }
</style>

<%= render 'main/navbar' %>

<div class="container d-flex justify-content-center align-items-center vh-100 vw-100" style="margin-top:10vh">
  <div class="welcome-message mt-4">
    <h4>Welcome, <%= @user_name_from_session %></h4>
  </div>

  <% if flash[:notice] %>
    <div class="alert alert-success text-center">
      <%= flash[:notice] %>
    </div>
  <% end %>

  <div class="container">
    <div class="row" style="height: 80px">
      <div class="col-md-6">
        <h1 style="font-weight: 500">Ongoing Challenges</h1>
      </div>
      <div class="col-md-3" style="display: flex; align-items: center; height: 80px">
        <button type="button" id="prev-challenge-btn" class="btn btn-primary btn-block" style="padding: 0;">
          <span style="font-size: 20px">&#8672;</span>
          Show Previous Challenges
        </button>
      </div>
      <div class="col-md-3"style="display: flex; align-items: center; height: 80px">
        <button type="button" id="upcoming-challenge-btn" class="btn btn-primary btn-block" style="padding: 0;">
          Show Upcoming Challenges
          <span style="font-size: 20px">&#8674;</span>
        </button>
      </div>
    </div>

    <div class="d-flex flex-wrap justify-content-center">
      <% @challenges.each do |challenge| %>
        <div class="row indiChallenge">
          <div class="challenge-content">
            <a href="<%= challenge_path(challenge) %>" class="challenge-tile" style="text-decoration: none;">
              <h2 style="font-size: 24px; font-weight: 500"><%= challenge.name %></h2>
            </a>
            <p style="display: inline; margin-right: 3em">Start Date: <%= challenge.startDate %></p>
            <p style="display: inline">End Date: <%= challenge.endDate %></p>
          </div>
        </div>
      <% end %>
    </div>
  </div>

  <%= will_paginate @challenges %>
  <div class="create-challenge-btn">
    <a href="<%= new_challenge_path %>" class="btn btn-primary" style="width: 16rem; padding: 5% 2%">Create Challenge</a>
  </div>
</div>


<script type="text/javascript">
  document.addEventListener('DOMContentLoaded', function() {
    const prevButton = document.getElementById('prev-challenge-btn');

    if (prevButton) {
      prevButton.addEventListener('click', function() {
        window.location.href = "<%= past_challenges_instructor_path @instructor.id %>";
      });
    }

    const uButton = document.getElementById('upcoming-challenge-btn');

    if (uButton) {
      uButton.addEventListener('click', function() {
        window.location.href = "<%= upcoming_challenges_instructor_path @instructor.id %>";
      });
    }
  });
</script>

app/views/instructors/show_future_challenges.html.erb
<style>
  .welcome-message h4 {
    color: black;
  }
  .create-challenge-btn {
    position: fixed;
    bottom: 20px;
    right: 20px;
  }
  .indiChallenge {
    border: solid 2px;
    overflow: hidden;
    margin: 1% 0;
  }
  .challenge-content {
    padding: 0 1% 1% 1%
  }
</style>

<%= render 'main/navbar' %>
<div class="container d-flex justify-content-center align-items-center vh-100 vw-100" style="margin-top:10vh">
  <div class="welcome-message mt-4">
    <h4>Welcome, <%= @user_name_from_session %></h4>
  </div>

  <% if flash[:notice] %>
    <div class="alert alert-success text-center">
      <%= flash[:notice] %>
    </div>
  <% end %>

  <div class="container">
    <div class="row" style="height: 80px">
      <div class="col-md-6">
        <h1 style="font-weight: 500">Upcoming Challenges</h1>
      </div>
      <div class="col-md-3"style="display: flex; align-items: center; height: 80px">
        <button type="button" id="prev-challenge-btn" class="btn btn-primary btn-block" style="padding: 0;">
          <span style="font-size: 20px">&#8606;</span>
          Show Past Challenges
        </button>
      </div>
      <div class="col-md-3" style="display: flex; align-items: center; height: 80px">
        <button type="button" id="ongoing-challenge-btn" class="btn btn-primary btn-block" style="padding: 0;">
          <span style="font-size: 20px">&#8672;</span>
          Show Ongoing Challenges
        </button>
      </div>
    </div>

    <div class="d-flex flex-wrap justify-content-center">
      <% @challenges.each do |challenge| %>
        <div class="row indiChallenge">
          <div class="challenge-content">
            <a href="<%= challenge_path(challenge) %>" class="challenge-tile" style="text-decoration: none;">
              <h2 style="font-size: 24px; font-weight: 500"><%= challenge.name %></h2>
            </a>
            <p style="display: inline; margin-right: 3em">Start Date: <%= challenge.startDate %></p>
            <p style="display: inline">End Date: <%= challenge.endDate %></p>
          </div>
        </div>
      <% end %>
    </div>
  </div>

  <%= will_paginate @challenges %>
  <a href="<%= new_challenge_path %>" class="btn btn-primary create-challenge-btn">Create Challenge</a>

</div>


<script type="text/javascript">
  document.addEventListener('DOMContentLoaded', function() {
    const b1 = document.getElementById('ongoing-challenge-btn');

    if (b1) {
      b1.addEventListener('click', function() {
        window.location.href = "<%= instructor_path @instructor.id %>";
      });
    }

    const prevButton = document.getElementById('prev-challenge-btn');

    if (prevButton) {
      prevButton.addEventListener('click', function() {
        window.location.href = "<%= past_challenges_instructor_path @instructor.id %>";
      });
    }
  });
</script>

app/views/instructors/show_prev_challenges.html.erb
<style>
  .welcome-message h4 {
    color: black;
  }
  .create-challenge-btn {
    position: fixed;
    bottom: 20px;
    right: 20px;
  }
  .indiChallenge {
    border: solid 2px;
    overflow: hidden;
    margin: 1% 0;
  }
  .challenge-content {
    padding: 0 1% 1% 1%
  }
</style>

<%= render 'main/navbar' %>
<div class="container d-flex justify-content-center align-items-center vh-100 vw-100" style="margin-top:10vh">
  <div class="welcome-message mt-4">
    <h4>Welcome, <%= @user_name_from_session %></h4>
  </div>

  <% if flash[:notice] %>
    <div class="alert alert-success text-center">
      <%= flash[:notice] %>
    </div>
  <% end %>

  <div class="container">
    <div class="row" style="height: 80px;">
      <div class="col-md-6">
        <h1 style="font-weight: 500">Past Challenges</h1>
      </div>
      <div class="col-md-3" style="display: flex; align-items: center; height: 80px">
        <button type="button" id="ongoing-challenge-btn" class="btn btn-primary btn-block" style="padding: 0;">
          Show Ongoing Challenges
          <span style="font-size: 20px">&#8674;</span>
        </button>
      </div>
      <div class="col-md-3"style="display: flex; align-items: center;height: 80px">
        <button type="button" id="upcoming-challenge-btn" class="btn btn-primary btn-block" style="padding: 0;">
          Show Upcoming Challenges
          <span style="font-size: 20px">&#8608;</span>
        </button>
      </div>
    </div>

    <div class="d-flex flex-wrap justify-content-center">
      <% @challenges.each do |challenge| %>
        <div class="row indiChallenge">
          <div class="challenge-content">
            <a href="<%= challenge_path(challenge) %>" class="challenge-tile" style="text-decoration: none;">
              <h2 style="font-size: 24px; font-weight: 500"><%= challenge.name %></h2>
            </a>
            <p style="display: inline; margin-right: 3em">Start Date: <%= challenge.startDate %></p>
            <p style="display: inline">End Date: <%= challenge.endDate %></p>
          </div>
        </div>
      <% end %>
    </div>
  </div>

  <%= will_paginate @challenges %>
  <a href="<%= new_challenge_path %>" class="btn btn-primary create-challenge-btn">Create Challenge</a>

</div>


<script type="text/javascript">
  document.addEventListener('DOMContentLoaded', function() {
    const b1 = document.getElementById('ongoing-challenge-btn');

    if (b1) {
      b1.addEventListener('click', function() {
        window.location.href = "<%= instructor_path @instructor.id %>";
      });
    }

    const b2 = document.getElementById('upcoming-challenge-btn');

    if (b2) {
      b2.addEventListener('click', function() {
        window.location.href = "<%= upcoming_challenges_instructor_path @instructor.id %>";
      });
    }
  });
</script>