config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  resources :users

  resources :sessions, only: %i[new create destroy]

  resources :instructors, only: [:show], param: :instructor_id do
    get 'past_challenges', on: :member, to: 'instructors#show_prev_challenges', as: 'past_challenges'
    get 'upcoming_challenges', on: :member, to: 'instructors#show_future_challenges', as: 'upcoming_challenges'
  end

  root 'sessions#new'
  get '/login', to: 'sessions#new', as: 'login'
  post '/login', to: 'sessions#create'
  get '/instructor_signup/:token/', to: 'instructors#new', as: 'instructor_signup'
  post '/instructor_signup/:token/', to: 'instructors#create'
  get '/signout', to: 'sessions#destroy', as: 'signout'

  get 'password/reset', to: 'password_resets#new'
  post 'password/reset', to: 'password_resets#create'
  get   'password/reset/edit', to: 'password_resets#edit'
  patch 'password/reset/edit', to: 'password_resets#update'

  get '/trainee_signup', to: 'trainee_signup#new', as: 'trainee_signup'
  post '/trainee_signup', to: 'trainee_signup#create'
  get 'instructor_referral', to: 'instructor_referral#index'
  post 'instructor_referral', to: 'instructor_referral#create'

  get '/todo_list', to: 'todo_list#show', as: 'todo_list'
  patch '/todo_list/mark_as_completed', to: 'todo_list#mark_as_completed', as: 'mark_as_complete'

  get '/trainees/:trainee_id', to: 'challenges#show_challenge_trainee', as: 'show_challenge_trainee'

  get '/trainees/:trainee_id/edit_todo_list/:challenge_id', to: 'todo_list#edit', as: 'edit_trainee_todo_list'
  patch '/trainees/:trainee_id/challenges/:challenge_id', to: 'todo_list#update', as: 'update_trainee_todo_list'

  get 'challenges', to: 'trainees#show_challenges', as: 'show_challenges'
  get '/view_challenge_tasks', to: 'view_challenge_tasks#index', as: 'view_challenge_tasks'
  get 'challenges/:id/challenge_details', to: 'view_challenge_tasks#challenge_details',
                                          as: 'view_challenge_tasks_detail'

  patch 'challenges/:id/todo_list_update', to: 'todo_list#todo_list_update', as: 'todo_list_patch' # update (as needed)
  get 'challenges/:id/todo_list_update', to: 'todo_list#todo_list_update', as: 'todo_list_update' # update (as needed)

  get '/view_trainees', to: 'view_trainees#index', as: 'view_trainees'
  get 'view_trainees/:id/profile_details', to: 'view_trainees#profile_details', as: 'trainee_profile_details'
  get 'view_trainees/:id/challenges', to: 'view_trainees#challenges', as: 'trainee_challenges'
  get 'view_trainees/:trainee_id/challenges/:challenge_id/progress', to: 'view_trainees#progress',
                                                                     as: 'trainee_challenge_progress'

  resources :challenges do
    member do
      get 'edit', to: 'challenges#edit'
      post 'update', to: 'challenges#update', as: 'update'
      get 'add_trainees', to: 'challenges#add_trainees' # This defines the "Add Users" action for a specific challenge
      post 'update_trainees', to: 'challenges#update_trainees' # This defines the action to handle form submission
      get '/delete_trainee', as: 'delete_trainee', controller: 'challenges', action: 'delete_trainee'
    end
  end

  resources :challenges do
    get '/trainees', controller: 'challenges', action: 'trainees_list', constraints: { query_string: /(.+)?/ },
                     as: 'list_trainees'
    get 'task_progress', on: :member, as: 'graph'
  end
  post 'filter_data' => 'challenges#filter_data'

  get '/profile', to: 'profiles#show', as: 'profile'
  get '/edit_profile', to: 'profiles#edit', as: 'edit_profile'
  patch '/update_profile', to: 'profiles#update', as: 'update_profile'

  get 'trainee_profile', to: 'trainee_profile#show'
  get 'edit_trainee_profile', to: 'trainee_profile#edit'
  patch 'trainee_profile', to: 'trainee_profile#update'
end

app/models/challenge.rb
# frozen_string_literal: true

class Challenge < ApplicationRecord
  has_many :challenge_genericlist
  has_many :challenge_trainees
  has_many :tasks, through: :challenge_genericlist
  has_many :trainees, through: :challenge_trainees
  accepts_nested_attributes_for :tasks, allow_destroy: true
  belongs_to :instructor
end

app/controllers/view_challenge_tasks_controller.rb
# frozen_string_literal: true

class ViewChallengeTasksController < ApplicationController
  rescue_from ActiveRecord::RecordNotFound, with: :task_not_found

  def index
    @user = User.find(session[:user_id])
  end

  def challenge_details
    @user = User.find(session[:user_id])
    @challenge = Challenge.find_by(id: params[:id])

    @user = User.find(session[:user_id])
    @is_instructor = @user.user_type.downcase == 'instructor'
    if @is_instructor
      @instructor = Instructor.find_by(user_id: @user.id)
      redirect_to instructor_path(@instructor) if @instructor
      return
    else
      trainee = Trainee.find_by(user_id: @user.id)
      @trainee = trainee
    end
    trainee_id = trainee.id

    @challenge_to_do_lists = []
    @trainee_challenges = ChallengeTrainee.where(trainee_id:)

    @challenge = Challenge.find_by(id: params[:id])

    selected_date = params[:selected_date]
    if selected_date.blank?
      selected_date = params.dig(:user, :selected_date)
      current_date = if selected_date.blank?
                       Date.today
                     else
                       Date.parse(selected_date)
                     end
    else
      current_date = Date.parse(selected_date)
    end
    (@challenge.startDate...@challenge.endDate).each do |ch_date|
      @todo_list = TodolistTask.where(trainee_id:, challenge_id: params[:id], date: ch_date).pluck(:task_id,
                                                                                                   :status, :date, :numbers)
      @challenge_to_do_lists << { challenge: @challenge, todo_list: @todo_list, date: ch_date }
    end

    @date = current_date

    return if @challenge

    flash[:alert] = 'task not found.'
    redirect_to view_challenge_tasks_detail_path
    nil
  end

  def challenge_not_found
    flash[:alert] = 'task not found.'
    redirect_to view_challenge_tasks_detail_path
  end
end

app/views/view_challenge_tasks/challenge_details.html.erb
<style>
  .show-challenges-btn {
    position: fixed;
    bottom: 20px;
    right: 20px;
  }

  .back-btn {
    position: fixed;
    bottom: 20px;
    right: 150px;
  }
</style>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.7.1/jquery.min.js"></script>
<script>
$(document).ready(function(){
  $("input").focus(function(){
    $(this).css("background-color", "#cccccc");
  });
  $("input").blur(function(){
    $(this).css("background-color", "#ffffff");
  });
	$("input").blur(function(){
		$(this).submit();
	});
});
</script>
<div>
  <div class="row" style="height: 80px">
    <%= render 'main/navbar' %>
  </div>
  
  <div class="container">
    <div class="row">
      <div class="col-md-10 col-md-offset-1" style="margin-top: 2%;">
        <% if flash[:notice] %>
          <div class="alert alert-success text-center">
            <%= flash[:notice] %>
          </div>
        <% elsif flash[:alert] %>
          <div class="alert alert-danger text-center">
            <%= flash[:alert] %>
          </div>
        <% end %>
				<%@date = Date.today%>
				<%params[:challenge_id] = @challenge.id%>
        <h2 style="margin: 1rem 0 2rem 0; font-weight: 500; text-align: center">  <%= @challenge.name %> </h2>
        <h2 style="margin: 1rem 0 2rem 0; font-weight: 500; text-align: center">Challenge Tracker </h2>
        <table class="table">
          <thead>
            <tr>
              <th>Tasks</th>
              <% @challenge_to_do_lists.each do |ch_todo| %>
                <th>  <%= ch_todo[:date].strftime("%B %d, %Y") %>  </th>

              <% end %>
            </tr>
          </thead>
          <tbody>
            <tr>
              <% @challenge.task_ids.each do |t_id| %>
                <tr>
                  <td>
                  <b>
										<%task = Task.find(t_id) %> 
										<%= task.taskName %> 
                  </b>
                  </td>
                  <% @challenge_to_do_lists.each do |ch_todo| %>
                    <% ch_todo[:todo_list].each do |task_id, status, date, old_nums| %>
										
                      <% if task_id === t_id %>
												<% if date === Date.today%>
													<td style="background-color:#8af788">
													<% @t = TodolistTask.find(task_id)%>
													<div class="col-xs-6">
														<%= form_with model: @user, url: todo_list_update_path, method: :patch do |f|%>	
																<%= f.hidden_field "tasks[#{task_id}][task_id]", value: task_id %>
																<%= f.hidden_field "tasks[#{task_id}][challenge_id]", value: @challenge.id %>
																<%= f.hidden_field "tasks[#{task_id}][date]", value: date %>
																<% task.numbers.each_with_index do |num, i|%>
																
																	<%if old_nums[i]%>
																		<%= f.number_field :numbers, multiple: true, value: old_nums[i]%>
																	<%else%>
																		<%= f.number_field :numbers, multiple: true%>
																	<%end%>
																<% end %>
																	
													
																<%= f.submit 'Update', class: "btn btn-primary" %>
															<% end %>
															</div>		
															</div>
												<% elsif date > Date.today%>
													<td style="background-color:#faf591">
													<% task.numbers.each_with_index do |num, i|%>
														<div class="col-xs-6">
															<input type="number" id="typeNumber" class="form-control" placeholder="<%=num%>" readonly/>
														</div>
													<% end %>
												<% elsif date < Date.today %>
													<td style="background-color:#f2786f">
													<% task.numbers.each_with_index do |num, i|%>
														<div class="col-xs-6">
															<input type="number" id="typeNumber" class="form-control" value="<%=old_nums[i]%>" readonly/>
														</div>
													<% end %>
												<% end %>
													
												</td>
                    <% end %>
                    <%end%>
                  <%end%>
                </tr>
              <% end %>               
            </tr>
          </tbody>
        </table>
       
        <div >
          <div class="btn back-btn" style="width: 16rem; padding: 0.5% 0.3%">
            <%= link_to "Back", :back %>
          </div>
          <a href="<%= show_challenges_path %>" class="btn btn-primary show-challenges-btn" style="width: 16rem; padding: 0.5% 0.3%">My Challenges</a>
        <div>
      </div>
    </div>
  </div>

</div>

app/views/view_challenge_tasks/index.html.erb
<%= render 'main/navbar' %>

<div style="padding-top: 60px;" class="container">
  <h1>View Trainees Page</h1>
  <% if @trainees_present %>
    <table class="table table-striped">
      <thead>
        <tr>
          <th>Trainee Name</th>
          <th>View Profile Button</th>
          <!-- add future headers here -->
        </tr>
      </thead>
      <tbody>
        <% @trainees.each do |trainee| %>
          <tr>
            <td><%= trainee.full_name %></td>
            <td>
              <%= link_to 'View Profile', trainee_profile_details_path(trainee), class: 'btn btn-primary' %>
              <!-- add future buttons here -->
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  <% else %>
    <p>No Trainees.</p>
  <% end %>
</div>