config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  resources :users

  resources :sessions, only: %i[new create destroy]

  resources :instructors, only: [:show], param: :instructor_id do
    get 'past_challenges', on: :member, to: 'instructors#show_prev_challenges', as: 'past_challenges'
    get 'upcoming_challenges', on: :member, to: 'instructors#show_future_challenges', as: 'upcoming_challenges'
  end

  root 'sessions#new'
  get '/login', to: 'sessions#new', as: 'login'
  post '/login', to: 'sessions#create'
  get '/instructor_signup/:token/', to: 'instructors#new', as: 'instructor_signup'
  post '/instructor_signup/:token/', to: 'instructors#create'
  get '/signout', to: 'sessions#destroy', as: 'signout'

  get 'password/reset', to: 'password_resets#new'
  post 'password/reset', to: 'password_resets#create'
  get   'password/reset/edit', to: 'password_resets#edit'
  patch 'password/reset/edit', to: 'password_resets#update'

  get '/trainee_signup', to: 'trainee_signup#new', as: 'trainee_signup'
  post '/trainee_signup', to: 'trainee_signup#create'
  get 'instructor_referral', to: 'instructor_referral#index'
  post 'instructor_referral', to: 'instructor_referral#create'

  get '/todo_list', to: 'todo_list#show', as: 'todo_list'
  patch '/todo_list/mark_as_completed', to: 'todo_list#mark_as_completed', as: 'mark_as_complete'

  get '/trainees/:trainee_id', to: 'challenges#show_challenge_trainee', as: 'show_challenge_trainee'

  get '/trainees/:trainee_id/edit_todo_list/:challenge_id', to: 'todo_list#edit', as: 'edit_trainee_todo_list'
  patch '/trainees/:trainee_id/challenges/:challenge_id', to: 'todo_list#update', as: 'update_trainee_todo_list'

  get 'challenges', to: 'trainees#show_challenges', as: 'show_challenges'
  get '/view_challenge_tasks', to: 'view_challenge_tasks#index', as: 'view_challenge_tasks'
  get 'challenges/:id/challenge_details', to: 'view_challenge_tasks#challenge_details',
                                          as: 'view_challenge_tasks_detail'

  patch 'challenges/:id/todo_list_update', to: 'todo_list#todo_list_update', as: 'todo_list_patch' # update (as needed)
  get 'challenges/:id/todo_list_update', to: 'todo_list#todo_list_update', as: 'todo_list_update' # update (as needed)

  get '/view_trainees', to: 'view_trainees#index', as: 'view_trainees'
  get 'view_trainees/:id/profile_details', to: 'view_trainees#profile_details', as: 'trainee_profile_details'
  get 'view_trainees/:id/challenges', to: 'view_trainees#challenges', as: 'trainee_challenges'
  get 'view_trainees/:trainee_id/challenges/:challenge_id/progress', to: 'view_trainees#progress',
                                                                     as: 'trainee_challenge_progress'

  resources :challenges do
    member do
      get 'edit', to: 'challenges#edit'
      post 'update', to: 'challenges#update', as: 'update'
      get 'add_trainees', to: 'challenges#add_trainees' # This defines the "Add Users" action for a specific challenge
      post 'update_trainees', to: 'challenges#update_trainees' # This defines the action to handle form submission
      get '/delete_trainee', as: 'delete_trainee', controller: 'challenges', action: 'delete_trainee'
    end
  end

  resources :challenges do
    get '/trainees', controller: 'challenges', action: 'trainees_list', constraints: { query_string: /(.+)?/ },
                     as: 'list_trainees'
    get 'task_progress', on: :member, as: 'graph'
  end
  post 'filter_data' => 'challenges#filter_data'

  get '/profile', to: 'profiles#show', as: 'profile'
  get '/edit_profile', to: 'profiles#edit', as: 'edit_profile'
  patch '/update_profile', to: 'profiles#update', as: 'update_profile'

  get 'trainee_profile', to: 'trainee_profile#show'
  get 'edit_trainee_profile', to: 'trainee_profile#edit'
  patch 'trainee_profile', to: 'trainee_profile#update'
end

app/controllers/todo_list_controller.rb
# frozen_string_literal: true

class TodoListController < ApplicationController
  before_action :require_user

  def new
    # @user = User.new
    # @trainee = Trainee.new
  end

  def show
    @user = User.find(session[:user_id])
    @is_instructor = @user.user_type.downcase == 'instructor'
    if @is_instructor
      @instructor = Instructor.find_by(user_id: @user.id)
      redirect_to instructor_path(@instructor) if @instructor
      return
    else
      trainee = Trainee.find_by(user_id: @user.id)
      @trainee = trainee
    end
    trainee_id = trainee.id

    @challenge_to_do_lists = []
    @trainee_challenges = ChallengeTrainee.where(trainee_id:)
    @trainee_challenges.each do |trainee_challenge|
      trainee_challenge_id = trainee_challenge.challenge_id
      @challenge = Challenge.find_by(id: trainee_challenge_id)

      selected_date = params[:selected_date]
      if selected_date.blank?
        selected_date = params.dig(:user, :selected_date)
        current_date = if selected_date.blank?
                         Date.today
                       else
                         Date.parse(selected_date)
                       end
      else
        current_date = Date.parse(selected_date)
      end
      @todo_list = TodolistTask.where(trainee_id:, challenge_id: trainee_challenge_id, date: current_date).pluck(
        :task_id, :status
      )
      @date = current_date
      if (current_date <= @challenge.endDate) && (current_date >= @challenge.startDate)
        streak = calculate_streak(trainee_id, trainee_challenge_id, current_date)
        @challenge_to_do_lists << { challenge: @challenge, todo_list: @todo_list, streak: }
      end
    end
  end

  def mark_as_completed
    if params[:user].present? && params[:user][:tasks].present?
      user_tasks = params[:user][:tasks]
    else
      redirect_to todo_list_path, notice: 'No Tasks'
      return
    end

    Date.today
    @user = User.find(session[:user_id])
    trainee = Trainee.find_by(user_id: @user.id)
    trainee_id = trainee.id

    user_tasks.each do |task_id, task_data|
      task_id = task_data[:task_id]
      challenge_id = task_data[:challenge_id]
      completed = task_data[:completed]
      current_date = task_data[:date]
      status = completed == '1' ? 'completed' : 'not_completed'

      @date = current_date
      task = TodolistTask.find_by(
        trainee_id:,
        task_id:,
        challenge_id:,
        date: current_date
      )

      next unless task

      task.update(status:) if status == 'completed'
    end

    redirect_to todo_list_path(selected_date: @date), notice: 'Tasks have been updated.'
  end

  def todo_list_update
    @user = User.find(session[:user_id])
    trainee = Trainee.find_by(user_id: @user.id)
    trainee_id = trainee.id

    current_date = Date.today
    user_tasks = params[:user][:tasks]

    user_tasks.each do |task_id, task_data|
      task_id = task_data[:task_id]
      challenge_id = task_data[:challenge_id]
      completed = task_data[:completed]
      current_date = task_data[:date]
      completed == '1' ? 'completed' : 'not_completed'

      @date = current_date
      task = TodolistTask.find_by(
        trainee_id:,
        task_id:,
        challenge_id:,
        date: current_date
      )
      if task.nil?
        redirect_to view_challenge_tasks_detail_path, notice: 'Tasks not found'
        return
      end
      new_data = params[:user][:numbers].map(&:to_f)
      task.update(numbers: new_data)
    end

    redirect_to view_challenge_tasks_detail_path, notice: 'Tasks have been updated.'
  end

  def update
    @user = User.find(session[:user_id])

    if @user.user_type == 'Instructor'
      # Handle task updates and deletions for instructors
      @trainee = Trainee.find(params[:trainee_id])
      @challenge = Challenge.find(params[:challenge_id])

      # Parse the start and end dates from the form
      start_date = Date.parse(params[:task][:start_date])
      end_date = Date.parse(params[:task][:end_date])

      # Check if the provided dates are within the challenge's start and end dates
      if start_date < @challenge.startDate || end_date > @challenge.endDate
        flash[:notice] = "Date range must be within the challenge's start and end dates."
        redirect_to edit_trainee_todo_list_path(@trainee, @challenge)
        return
      elsif start_date <= Date.today
        flash[:notice] = 'Challenge has already started! Choose a start date from tomorrow onwards.'
        redirect_to edit_trainee_todo_list_path(@trainee, @challenge)
        return
      end

      TodolistTask.where(trainee: @trainee, challenge: @challenge, date: start_date..end_date).destroy_all

      # Process submitted tasks
      if params.key?(:task)
        task_from_params = params.dig(:task, :tasks)

        if task_from_params.present?
          task_from_params.each do |id, task_params|
            existing_task = Task.find(id)

            if existing_task.taskName != task_params[:taskName]
              # Name changed, make a new task
              task = Task.create(taskName: task_params[:taskName])
              task.id # Update the id
            else
              task = existing_task
            end

            (start_date..end_date).each do |date|
              TodolistTask.create(
                trainee: @trainee,
                challenge: @challenge,
                task:,
                date:,
                status: 'not_completed'
              )
            end
          end
        end
      end

      new_tasks = params[:tasks]
      if new_tasks && !new_tasks.empty?
        new_tasks.each_value do |task_params|
          existing_task = Task.find_by(taskName: task_params[:taskName])

          task = existing_task || Task.create(taskName: task_params[:taskName])

          (start_date..end_date).each do |date|
            TodolistTask.create(
              trainee: @trainee,
              challenge: @challenge,
              task:,
              date:,
              status: 'not_completed'
            )
          end
        end
      end

      redirect_to edit_trainee_todo_list_path(@trainee, @challenge), notice: 'Tasks successfully updated.'
    else
      trainee = Trainee.find_by(user_id: @user.id)
      trainee_id = trainee.id
      trainee_challenge_id = ChallengeTrainee.find_by(trainee_id:).challenge_id
      current_date = Date.today
      task_params = params[:tasks] || {}
      nums = params[:numbers]
      puts params
      task_params.each do |task_id, status|
        TodolistTask.find_by(id: task_id, date: @date).update(status:, numbers: nums)
      end
      @todo_list = TodolistTask.where(trainee_id:, challenge_id: trainee_challenge_id, date: current_date).pluck(
        :task_id, :status
      )
      @date = current_date
      redirect_to todo_list_path, notice: 'Tasks have been updated.'
    end
  end

  def edit
    @instructor = Instructor.find_by(user_id: session[:user_id])

    if @instructor
      @trainee = Trainee.find(params[:trainee_id])
      @challenge = Challenge.find(params[:challenge_id])

      todo_date = if @challenge.startDate <= Date.today
                    Date.today
                  else
                    @challenge.startDate
                  end

      task_ids = TodolistTask.where(trainee_id: @trainee.id, challenge_id: @challenge.id,
                                    date: todo_date).pluck(:task_id)
      @todo_list = Task.where(id: task_ids)
    else
      flash[:notice] = 'You are not an instructor.'
      redirect_to root_path
    end
  end

  def calculate_streak(trainee_id, challenge_id, current_date)
    todolist_tasks = TodolistTask.where(trainee_id:, challenge_id:).order(date: :asc)

    streak_counters = Hash.new(0)

    todolist_tasks.each do |task|
      break if task.date == current_date

      streak_counters[task.task_id] ||= 0
      if task.status == 'completed'
        streak_counters[task.task_id] += 1
      else
        streak_counters[task.task_id] = 0
      end
    end

    streak_counters
  end

  private

  def require_user
    return if user_signed_in?

    flash[:alert] = 'You must be signed in to access this page.'
    redirect_to login_path
  end
end

app/helpers/todo_list_helper.rb
# frozen_string_literal: true

module TodoListHelper
  def best_days(challenge_id, trainee_id)
    @challenge = Challenge.find_by(id: challenge_id)

    return 0 unless @challenge.startDate <= Date.today

    end_date = if @challenge.endDate < Date.today
                 @challenge.endDate
               else
                 Date.today
               end

    start_date = @challenge.startDate

    counter = 0
    (start_date..end_date).each do |date|
      tasks = TodolistTask.where(challenge_id:, trainee_id:, date:)

      counter += 1 if tasks.all? { |task| task.status == 'completed' }
    end

    counter
  end
end

app/views/todo_list/edit.html.erb
<%= render 'main/navbar' %>

<div class="container" style="margin-top: 8%;">
  <% if flash[:notice] %>
    <div class="alert alert-success text-center">
      <%= flash[:notice] %>
    </div>
  <% elsif flash[:alert] %>
    <div class="alert alert-danger text-center">
      <%= flash[:alert] %>
    </div>
  <% end %>

  <div class="row" style="text-align: center; margin-bottom: 2%">
    <h2 style="font-weight: 500">Current Todo List: <%= Trainee.find(params[:trainee_id]).full_name %></h2>
  </div>

  <div class="row" style="margin-bottom: 2%">
    <div class="col-md-6 col-md-offset-3">
      <%= form_with model: @todo_list, url: update_trainee_todo_list_path(@trainee, @challenge), method: :patch, id: "update-todo-list-form" do |f| %>
        <div class="form-group">
          <label for="start_date">Start Date</label>

          <% if @challenge.startDate <= Date.today %>
            <%= f.date_field :start_date, class: 'form-control', value: Date.today, id: 'start_date' %>
          <% else %>
            <%= f.date_field :start_date, class: 'form-control', value: @challenge.startDate, id: 'start_date' %>
          <% end %>
        </div>
        
        <div class="form-group">
          <label for "end_date">End Date</label>
          <%= f.date_field :end_date, class: 'form-control', value: @challenge.endDate, id: 'end_date' %>
        </div>
        
        <div class="form-group">
          <label for "tasks">Tasks</label>
          <ol id="task-list">
            <% @todo_list.each_with_index do |task, i| %>
              <li>
                <%= f.text_field "tasks[#{task.id}][taskName]", value: task.taskName, class: 'form-control' %>
                <button class="btn btn-danger btn-circle delete-task-button">Delete</button> 
              </li>
            <% end %>
          </ol>
        </div>

        <button type="button" id="add-task-button" class="btn btn-success" style="margin-bottom: 1%">Add Task</button>

        <div class="actions">
          <%= f.submit 'Update', class: 'btn btn-primary' %>
        </div>
      <% end %>
    </div>
  </div>
</div>

<script>
document.addEventListener("DOMContentLoaded", function() {
  const addTaskButton = document.getElementById("add-task-button");
  const taskList = document.getElementById("task-list");
  let taskIndex = <%= @todo_list.count %>; // Set the initial task index based on existing tasks

  // Handle adding a new task
  addTaskButton.addEventListener("click", function() {
    const taskForm = `<li>
      <input type="text" name="tasks[new_${taskIndex}][taskName]" class="form-control">
      <button class="btn btn-danger btn-circle delete-task-button">Delete</button>
    </li>`;

    taskList.insertAdjacentHTML("beforeend", taskForm);
    taskIndex++;
  });

  // Handle removing tasks
  taskList.addEventListener("click", function(e) {
    if (e.target.classList.contains("delete-task-button")) {
      e.preventDefault();
      const taskItem = e.target.closest("li");
      taskItem.remove();
    }
  });

  // Submit the form
  const updateTodoListForm = document.getElementById("update-todo-list-form");
  if (updateTodoListForm) {
    updateTodoListForm.addEventListener("submit", function() {
      // Additional validation or actions before submitting the form, if needed
    });
  }
});
</script>

app/views/todo_list/show.html.erb
<style>
  .content-box {
    border: 2px solid;
    padding: 5px;
  }

  .checkbox-cell {
    padding-right: 5px;
  }

  .task-name-cell s {
    text-decoration: line-through;
  }

  .show-challenges-btn {
    position: fixed;
    bottom: 20px;
    right: 20px;
  }
</style>

<div>
  <div class="row" style="height: 80px">
    <%= render 'main/navbar' %>
  </div>
  <div class="container">
    <div class="row">
      <div class="col-md-6 col-md-offset-3" style="margin-top: 2%;">
        <% if flash[:notice] %>
          <div class="alert alert-success text-center">
            <%= flash[:notice] %>
          </div>
        <% elsif flash[:alert] %>
          <div class="alert alert-danger text-center">
            <%= flash[:alert] %>
          </div>
        <% end %>

        <h2 style="margin: 1rem 0 2rem 0; font-weight: 500">Daily Todo List</h2>

        <div>
          <%= form_with model: @user, url: todo_list_path, method: :get, data: { turbo: false } do |f| %>
            <div class="form-group" style="margin-bottom: 5px">
              <%= f.label :selected_date, 'Select Date' %>
              <%= f.date_field :selected_date, class: 'form-control' %>
            </div>
            <%= f.submit 'Show Tasks', class: 'btn btn-primary', style: "margin-bottom: 5px" %>
            <div class="text-center" style="margin-bottom: 5px">
              <span>Streak: 🔥</span>
              <span>Total Best Days: 🎯</span> 
            </div>
          <% end %>
        </div>
      
        <% @challenge_to_do_lists.each do |challenge_todo| %>
          <div class="card" style="box-shadow: 0 0 10px rgba(0, 0, 0, 0.2); border: 1px solid #000; padding: 2%;">
            <div>
              <h3 style="margin-top: 0; font-weight: 500"><%= challenge_todo[:challenge].name %></h3>
              <p>Date: <%= @date.strftime("%B %d, %Y") %></p>
        
              <%= form_with model: @user, url: mark_as_complete_path, method: :patch, data: { turbo: false } do |f| %>
                <ul class="list-group" style="margin-bottom: 1rem">
                  <table >
                    <tbody>
                      <% challenge_todo[:todo_list].each do |task_id, status| %>
                        <tr>
                          <td class="checkbox-cell">
                            <%= f.hidden_field "tasks[#{task_id}][task_id]", value: task_id %>
                            <%= f.hidden_field "tasks[#{task_id}][challenge_id]", value: challenge_todo[:challenge].id %>
                            <%= f.hidden_field "tasks[#{task_id}][date]", value: @date %>
                            <%= f.check_box "tasks[#{task_id}][completed]", { class: 'task-checkbox' }, "1", "0" %>
                          </td>
                          <td class="task-name-cell">
                            <% if status == "completed" %>
                              <s><%= Task.find(task_id).taskName %></s> 🔥<%= challenge_todo[:streak][task_id]%>
                            <% else %>
                              <%= Task.find(task_id).taskName %> 🔥<%= challenge_todo[:streak][task_id]%>
                            <% end %>
                          </td>
                        </tr>
                      <% end %>
                    </tbody>
                  </table>
                </ul>

                <div>
                  🎯 <%= best_days(challenge_todo[:challenge].id, Trainee.find_by(user_id: @user.id).id) %>
                </div>
        
                <div class="text-center">
                  <% if @date.present? %>
                    <% if @date == Date.today %>
                      <%= f.submit 'Mark as Completed', class: "btn btn-primary" %>
                    <% elsif @date == Date.today - 1 && Time.now.hour <= 3 %>
                      <%= f.submit 'Mark as Completed', class: "btn btn-primary" %>
                    <% else %>
                      <%= f.submit 'Mark as Completed', class: "btn btn-primary", disabled: true %>
                    <% end %>
                  <% end %>
                  <%= link_to 'View Progress', graph_challenge_path(@challenge, trainee_id: @trainee.id), class: 'btn btn-primary' %>
                </div>
              <% end %>
            </div>
          </div>
        <% end %>

        <div style="position: fixed; bottom: 2rem; right: 2rem;">
          <a href="<%= show_challenges_path %>" class="btn btn-primary show-challenges-btn" style="width: 16rem; padding: 0.5% 0.3%">My Challenges</a>
        <div>
      </div>
    </div>
  </div>

</div>